package com.dunamis.leadManagement.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * Lead Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "Lead")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "Dunamis2Rest/com/dunamis/leadManagement/domain", name = "Lead")
public class Lead implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "lead")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String lead;

    @Column(name = "date")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date date;
    
    
    @ManyToOne
    @JoinColumn(name="productId")
    private Product product;
    
    @ManyToOne
    @JoinColumn(name="customerId")
    private Customer customer;
    
    @ManyToOne
    @JoinColumn(name="organizationId")
    private Organization organization;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getLead() {
        return lead;
    }
    
    public void setLead(String lead) {
        this.lead = lead;
    }
    
    public Product getProduct() {
        return product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    
    public Customer getCustomer() {
        return customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    
    public Date getDate() {
        return date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    public Organization getOrganization() {
        return organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }


    public Lead() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof Lead))
            return false;
        Lead equalCheck = (Lead) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}